# Generated by Django 4.0.5 on 2022-07-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0012_alter_paciente_immediate_background_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='adendums',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Imagenología1',
            field=models.FileField(blank=True, help_text='formato jpg, jpge', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Imagenología2',
            field=models.FileField(blank=True, help_text='formato jpg, jpge', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Imagenología3',
            field=models.FileField(blank=True, help_text='formato jpg, jpge', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Labs1',
            field=models.FileField(blank=True, help_text='formato pdf', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Labs2',
            field=models.FileField(blank=True, help_text='formato pdf', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='recetas',
            field=models.FileField(blank=True, help_text='formato pdf', null=True, upload_to='Paciente/', verbose_name='Recetas'),
        ),
    ]
