# Generated by Django 4.0.6 on 2022-08-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0013_paciente_adendums_alter_paciente_imagenología1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.SmallIntegerField(default=0)),
                ('im_bkground', models.TextField(verbose_name='Antecedentes Inmediatos')),
                ('other_bkground', models.TextField(verbose_name='Otros Antecedentes')),
                ('tension_sistolica', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('tension_diastolica', models.PositiveSmallIntegerField(blank=True, default=1, null=True)),
                ('pam', models.IntegerField(default=0, verbose_name='PAM')),
                ('fc', models.IntegerField(blank=True, null=True, verbose_name='FC')),
                ('fr', models.IntegerField(blank=True, null=True, verbose_name='FR')),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp')),
                ('saturacion', models.IntegerField(blank=True, null=True, verbose_name='Sa02')),
                ('PaFI', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dextrostix', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dextrostix')),
                ('a1c', models.CharField(blank=True, max_length=5, null=True)),
                ('peso', models.FloatField(blank=True, default=0, null=True)),
                ('estatura', models.FloatField(blank=True, default=1, null=True)),
                ('imc', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IMC')),
                ('climc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Clasificación Masa Corporal')),
                ('asc', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ASC')),
                ('per_abdominal', models.IntegerField(blank=True, null=True, verbose_name='Per. Abd en cms')),
                ('AVPU', models.CharField(choices=[('Alerta', 'Alerta'), ('Respuesta Verbal', 'Respuesta Verbal'), ('Respuesta al Dolor', 'Respuesta al Dolor'), ('Sin Respuesta', 'Sin Respuesta')], max_length=50, verbose_name='Estado de Conciencia')),
                ('apertura_ocular', models.PositiveSmallIntegerField(blank=True, choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=1, null=True)),
                ('Respuesta_Verbal', models.PositiveSmallIntegerField(blank=True, choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, null=True)),
                ('Respuesta_Motora', models.PositiveSmallIntegerField(blank=True, choices=[(6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], null=True)),
                ('ESCALA_DE_GLASGOW', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expl', models.TextField(blank=True, null=True, verbose_name='Complemente Exploración')),
                ('DIAGNOSTICOS', models.TextField(blank=True, null=True)),
                ('MANEJO_INICIAL', models.TextField(blank=True, null=True)),
                ('nombre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
            options={
                'verbose_name_plural': 'c) Urgencias, Evaluación Primaria',
            },
        ),
    ]
