# Generated by Django 4.0.6 on 2022-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0014_urgencias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgencias',
            name='DIAGNOSTICOS',
        ),
        migrations.AddField(
            model_name='urgencias',
            name='dxs',
            field=models.TextField(blank=True, null=True, verbose_name='DIAGNOSTICOS'),
        ),
    ]
