# Generated by Django 4.0.6 on 2022-08-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0015_remove_urgencias_diagnosticos_urgencias_dxs'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias',
            name='CONSIDERACIONES',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='Respuesta_Motora',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, null=True),
        ),
    ]
