# Generated by Django 4.0.6 on 2022-08-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0016_urgencias_consideraciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias',
            name='Diaforesis',
            field=models.CharField(blank=True, choices=[('POS', 'Positivo'), ('NEG', 'Negativo')], max_length=100, null=True),
        ),
    ]
