# Generated by Django 4.0.6 on 2022-08-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0017_urgencias_diaforesis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgencias',
            name='CONSIDERACIONES',
        ),
        migrations.AddField(
            model_name='urgencias',
            name='NEUROLOGICO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
