# Generated by Django 4.0.6 on 2022-08-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0018_remove_urgencias_consideraciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias',
            name='HEMODINAMICO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
