# Generated by Django 4.0.6 on 2022-08-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0020_rename_pafi_urgencias_o2_remove_urgencias_a1c_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias',
            name='RESPIRATORIO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='FiO2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
