# Generated by Django 4.0.6 on 2022-08-12 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0021_urgencias_respiratorio_alter_urgencias_fio2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias',
            name='ESCALA_DE_GLASGOW',
            field=models.PositiveSmallIntegerField(blank=True, help_text='sume los parámetros', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='FiO2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='No escriba aquí', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='O2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='En litros/min', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='Respuesta_Motora',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='Respuesta_Verbal',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='SpFI',
            field=models.PositiveSmallIntegerField(blank=True, help_text='No escriba aquí', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='apertura_ocular',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='asc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='No escriba aquí', max_digits=5, verbose_name='ASC'),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='climc',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True, verbose_name='Clasificación Masa Corporal'),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='estatura',
            field=models.FloatField(blank=True, default=0.0, help_text='En metros y cms', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='imc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='No escriba aquí', max_digits=5, verbose_name='IMC'),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='pam',
            field=models.IntegerField(default=0, help_text='No escriba aquí', verbose_name='PAM'),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='tension_diastolica',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='tension_sistolica',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
