# Generated by Django 4.0.6 on 2022-08-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0022_alter_urgencias_escala_de_glasgow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias',
            name='INFECCIOSO',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urgencias',
            name='qSOFA',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='HEMODINAMICO',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='MANEJO_INICIAL',
            field=models.TextField(blank=True, help_text='No escriba aquí', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='NEUROLOGICO',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='RESPIRATORIO',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True),
        ),
    ]
