# Generated by Django 4.0.6 on 2022-08-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0023_urgencias_infeccioso_urgencias_qsofa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgencias',
            name='qSOFA',
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='peso',
            field=models.FloatField(blank=True, default=0, help_text='No no puede pesar al paciente, calcule un aproximado', null=True),
        ),
    ]
