# Generated by Django 4.0.6 on 2022-08-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0024_remove_urgencias_qsofa_alter_urgencias_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='AVPU',
            field=models.CharField(blank=True, choices=[('Alerta', 'Alerta'), ('Respuesta Verbal', 'Respuesta Verbal'), ('Respuesta al Dolor', 'Respuesta al Dolor'), ('Sin Respuesta', 'Sin Respuesta')], max_length=50, null=True, verbose_name='Estado de Conciencia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='RECOMENDACIONES',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='MANEJO_INICIAL',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='peso',
            field=models.FloatField(blank=True, default=0, help_text='Si no puede pesar al paciente, calcule un aproximado', null=True),
        ),
    ]
