# Generated by Django 4.0.6 on 2022-08-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0025_paciente_avpu_paciente_recomendaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias',
            name='FiO2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.21, help_text='No escriba aquí', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='estatura',
            field=models.FloatField(blank=True, default=1, help_text='En metros y cms', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='saturacion',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Sa02'),
        ),
    ]
