# Generated by Django 4.1 on 2022-08-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0026_alter_urgencias_fio2_alter_urgencias_estatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias',
            name='AVPU',
            field=models.CharField(blank=True, choices=[('Alerta', 'Alerta'), ('Respuesta Verbal', 'Respuesta Verbal'), ('Respuesta al Dolor', 'Respuesta al Dolor'), ('Sin Respuesta', 'Sin Respuesta')], max_length=50, null=True, verbose_name='Estado de Conciencia'),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='O2',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='En litros/min', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='fc',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='FC'),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='fr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='FR'),
        ),
    ]
