# Generated by Django 4.1 on 2022-08-31 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0027_alter_urgencias_avpu_alter_urgencias_o2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urgencias',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'c) Urgencias, Evaluación Primaria'},
        ),
        migrations.AddField(
            model_name='urgencias',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='urgencias',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
    ]
