# Generated by Django 4.0.6 on 2022-09-04 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0028_alter_urgencias_options_urgencias_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias',
            name='nombre',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente'),
        ),
    ]
