# Generated by Django 4.0.6 on 2022-09-07 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0030_alter_urgencias_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias',
            name='actual_situation',
            field=models.TextField(blank=True, null=True, verbose_name='Situación Actual y Exploración'),
        ),
    ]
