# Generated by Django 4.0.6 on 2022-09-10 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0032_remove_urgencias_actual_situation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono'),
        ),
    ]
