# Generated by Django 4.0.6 on 2022-09-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0033_alter_paciente_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias',
            name='Respuesta_Motora',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, help_text='Obedece órdenes 6; Localiza dolor 5; Retirada al dolor 4; Flexión anormal 3; Extensión anormal 2; Ausencia de Respuesta 1.', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='Respuesta_Verbal',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, help_text='Orientado 5; Desorientado confuso 4; Incoherente 3; Sonidos incomprensibles 1.', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='apertura_ocular',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=1, help_text='Espontánea 4; Orden verbal 3; Est. Doloroso 2; No Apertura 1.', null=True),
        ),
    ]
