# Generated by Django 4.1.1 on 2022-09-13 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0034_alter_urgencias_respuesta_motora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgencias_Reevaluaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.SmallIntegerField(default=0)),
                ('evaluacion_sec', models.CharField(blank=True, choices=[('Primera Evaluación', 'Primera Evaluación'), ('Segunda Evaluación', 'Segunda Evaluación'), ('Tercera Evaluación', 'Tercera Evalaución'), ('Cuarta Evaluación', 'Cuarta Evaluación'), ('Quinta Evaluación', 'Quinta Evaluación'), ('Sexta Evaluación', 'Sexta Evaluación'), ('Séptima Evaluación', 'Séptima Evaluación'), ('Octava Evaluación', 'Octava Evaluación')], max_length=50, null=True, verbose_name='Evaluación Subsecuente')),
                ('dxs_previos', models.TextField(blank=True, null=True)),
                ('sit_actual', models.TextField(blank=True, null=True, verbose_name='Situación Actual')),
                ('Diaforesis', models.CharField(blank=True, choices=[('POS', 'Positivo'), ('NEG', 'Negativo')], max_length=100, null=True)),
                ('fr', models.IntegerField(blank=True, default=0, null=True, verbose_name='FR')),
                ('O2', models.PositiveSmallIntegerField(blank=True, default=0, help_text='En litros/min', null=True)),
                ('FiO2', models.DecimalField(blank=True, decimal_places=2, default=0.21, help_text='No escriba aquí', max_digits=5, null=True)),
                ('saturacion', models.IntegerField(blank=True, default=1, null=True, verbose_name='Sa02')),
                ('SpFI', models.PositiveSmallIntegerField(blank=True, help_text='No escriba aquí', null=True)),
                ('fc', models.IntegerField(blank=True, default=0, null=True, verbose_name='FC')),
                ('tension_sistolica', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('tension_diastolica', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('pam', models.IntegerField(default=0, help_text='No escriba aquí', verbose_name='PAM')),
                ('dextrostix', models.IntegerField(blank=True, default=0, null=True, verbose_name='Dextrostix')),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temp')),
                ('peso', models.FloatField(blank=True, default=0, help_text='Si no puede pesar al paciente, calcule un aproximado', null=True)),
                ('estatura', models.FloatField(blank=True, default=1, help_text='En metros y cms', null=True)),
                ('imc', models.DecimalField(decimal_places=2, default=0, help_text='No escriba aquí', max_digits=5, verbose_name='IMC')),
                ('climc', models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True, verbose_name='Clasificación Masa Corporal')),
                ('asc', models.DecimalField(decimal_places=2, default=0, help_text='No escriba aquí', max_digits=5, verbose_name='ASC')),
                ('per_abdominal', models.IntegerField(blank=True, null=True, verbose_name='Per. Abd en cms')),
                ('AVPU', models.CharField(blank=True, choices=[('Alerta', 'A Alerta'), ('Respuesta Verbal', 'V Respuesta Verbal'), ('Respuesta al Dolor', 'P Respuesta al Dolor'), ('Sin Respuesta', 'U Sin Respuesta')], max_length=50, null=True, verbose_name='Estado de Conciencia')),
                ('apertura_ocular', models.PositiveSmallIntegerField(blank=True, choices=[(4, 4), (3, 3), (2, 2), (1, 1)], default=1, help_text='Espontánea 4; Orden verbal 3; Est. Doloroso 2; No Apertura 1.', null=True)),
                ('Respuesta_Verbal', models.PositiveSmallIntegerField(blank=True, choices=[(5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, help_text='Orientado 5; Desorientado confuso 4; Incoherente 3; Sonidos incomprensibles 1.', null=True)),
                ('Respuesta_Motora', models.PositiveSmallIntegerField(blank=True, choices=[(6, 6), (5, 5), (4, 4), (3, 3), (2, 2), (1, 1)], default=1, help_text='Obedece órdenes 6; Localiza dolor 5; Retirada al dolor 4; Flexión anormal 3; Extensión anormal 2; Ausencia de Respuesta 1.', null=True)),
                ('ESCALA_DE_GLASGOW', models.PositiveSmallIntegerField(blank=True, help_text='sume los parámetros', null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultorio.paciente')),
            ],
        ),
    ]
