# Generated by Django 4.1.1 on 2022-09-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0035_urgencias_reevaluaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urgencias_reevaluaciones',
            name='FiO2',
        ),
        migrations.RemoveField(
            model_name='urgencias_reevaluaciones',
            name='SpFI',
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='FrIO2',
            field=models.FloatField(blank=True, default=0.21, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='FrecResp',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Frec, Resp.'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='PEEP',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Pinsp',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Presion Insp'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Tinsp',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tiempo Insp (Peak Flow'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Vt',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True, verbose_name='Vol. Corriente (Vt)'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='mode',
            field=models.CharField(blank=True, choices=[('VAC', 'VAC'), ('PAC', 'PAC'), ('VSIMC', 'VSIMC'), ('PSIMC', 'PSIMC'), ('Psup', 'Psup')], max_length=7, null=True, verbose_name='Modo Ventilatorio'),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='evaluacion_sec',
            field=models.CharField(blank=True, choices=[('Segunda Evaluación', 'Segunda Evaluación'), ('Tercera Evaluación', 'Tercera Evalaución'), ('Cuarta Evaluación', 'Cuarta Evaluación'), ('Quinta Evaluación', 'Quinta Evaluación'), ('Sexta Evaluación', 'Sexta Evaluación'), ('Séptima Evaluación', 'Séptima Evaluación'), ('Octava Evaluación', 'Octava Evaluación')], max_length=50, null=True, verbose_name='Evaluación Subsecuente'),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='fr',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Frec. Resp'),
        ),
    ]
