# Generated by Django 4.1.1 on 2022-09-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0036_remove_urgencias_reevaluaciones_fio2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Sens',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias',
            name='ESCALA_DE_GLASGOW',
            field=models.PositiveSmallIntegerField(blank=True, help_text='No escriba aquí', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='ESCALA_DE_GLASGOW',
            field=models.PositiveSmallIntegerField(blank=True, help_text='No escriba aquí', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='Tinsp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tiempo Insp (Peak Flow)'),
        ),
    ]
