# Generated by Django 4.1.1 on 2022-09-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0037_urgencias_reevaluaciones_sens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Rx_Tórax',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4)], null=True, verbose_name='Cuadrantes Afectados en Rx de Tórax'),
        ),
    ]
