# Generated by Django 4.1.1 on 2022-09-13 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0038_urgencias_reevaluaciones_rx_tórax'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='lung_compl',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='No esciba aquí', max_digits=5, null=True, verbose_name='Complianza Pulmonar'),
        ),
    ]
