# Generated by Django 4.1.1 on 2022-09-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0039_urgencias_reevaluaciones_lung_compl'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='pit',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Presión Intratorácica Total'),
        ),
    ]
