# Generated by Django 4.1.1 on 2022-09-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0041_rename_rx_tórax_urgencias_reevaluaciones_rx_torax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urgencias_reevaluaciones',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'c) Urgencias, Evaluaciones Subsecuentes'},
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Ca',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Creatinina',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='DHL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='EB',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='HCO3',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='K',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Lactato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Mg',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Na',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='P',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='PCR',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='TGO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='TGP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Urea',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='basofilos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='bilirrTot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='compl_ex',
            field=models.TextField(blank=True, null=True, verbose_name='Complemento Exploración'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='eosinofilos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='glucosa',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='hb',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='hto',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='interconsulta',
            field=models.CharField(blank=True, choices=[('Medicina Interna', 'Medicina Interna'), ('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('NEUROLOGÍA', 'Neurología'), ('Neurocirugía', 'Neurocirugía'), ('Ortopedia', 'Ortopedia'), ('Ginecología', 'Ginecología'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='leucocitos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='linfocitos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='neutrofilos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='pCO2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='pH',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='reest_man',
            field=models.TextField(blank=True, null=True, verbose_name='Reestructuración o Cambios en el Manejo'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='update',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='O2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='pit',
            field=models.PositiveSmallIntegerField(blank=True, help_text='No escriba aquí, OJO: Son Kgs.', null=True, verbose_name='Presión Intratorácica Total'),
        ),
    ]
