# Generated by Django 4.1.1 on 2022-09-15 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0042_alter_urgencias_reevaluaciones_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urgencias_reevaluaciones',
            options={'ordering': ('-timestamp',), 'verbose_name_plural': 'd) Urgencias, Evaluaciones Subsecuentes'},
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='HEMODINAMICO',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='INFECCIOSO',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='NEUROLOGICO',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='RESPIRATORIO',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True),
        ),
    ]
