# Generated by Django 4.1.1 on 2022-09-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0043_alter_urgencias_reevaluaciones_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='sO2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='EB',
            field=models.PositiveSmallIntegerField(blank=True, help_text='mmol/L', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='HCO3',
            field=models.PositiveSmallIntegerField(blank=True, help_text='mmol/L', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='O2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='mm/Hg', null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='pCO2',
            field=models.PositiveSmallIntegerField(blank=True, help_text='mm/Hg', null=True),
        ),
    ]
