# Generated by Django 4.1.1 on 2022-09-16 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0044_urgencias_reevaluaciones_so2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='PaFI',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='VALORES',
            field=models.CharField(blank=True, help_text='No escriba aquí', max_length=100, null=True, verbose_name='VALORES ANORMALES'),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='EB',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='mmol/L', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='HCO3',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='mmol/L', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='hb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='g/dL', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='hto',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='%', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='pCO2',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='mm/Hg', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='pH',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True),
        ),
    ]
