# Generated by Django 4.1.1 on 2022-09-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0047_urgencias_reevaluaciones_labs1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='pO2',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='mm/Hg', null=True, verbose_name='pO2'),
        ),
    ]
