# Generated by Django 4.1.1 on 2022-09-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0049_urgencias_reevaluaciones_metabolico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='meds_dosis',
            field=models.TextField(blank=True, help_text='Mencione medicamentos y dosis de sedación', null=True, verbose_name='Medicamentos y Dosis'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='vent_mec',
            field=models.CharField(blank=True, choices=[('POS', 'Positivo'), ('NEG', 'Negativo')], max_length=10, null=True, verbose_name='Ventilación Mecánica'),
        ),
    ]
