# Generated by Django 4.1.1 on 2022-09-16 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0050_urgencias_reevaluaciones_meds_dosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='RASS',
            field=models.CharField(blank=True, choices=[('+4', '+4 Combativo'), ('+3', '+3 Muy agitado'), ('+2', '+2 Agitado'), ('+1', '+1 Inquieto'), ('0 Despierto y Tranquilo', '0 Despierto y tranuilo'), ('-1', '-1 Somnoliento'), ('-2', '-2 Sedación leve'), ('-3', '-3 Sedación moderada'), ('-4', '-4 Sedación profunda'), ('-5', '-5 Sin respuesta')], max_length=30, null=True),
        ),
    ]
