# Generated by Django 4.1.1 on 2022-09-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0051_alter_urgencias_reevaluaciones_rass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='Diaforesis',
            field=models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='Sedacion',
            field=models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='vent_mec',
            field=models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=10, null=True, verbose_name='Ventilación Mecánica'),
        ),
    ]
