# Generated by Django 4.1.1 on 2022-09-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0052_alter_urgencias_reevaluaciones_diaforesis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='diuresis',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Diuresis hasta el momento actual desde su ingreso '),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='ingreso_iv',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Ingreso IV hasta el momento actual desde su ingreso'),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='compl_ex',
            field=models.TextField(blank=True, null=True, verbose_name='Complemente exploración torácica'),
        ),
    ]
