# Generated by Django 4.1.1 on 2022-09-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0054_urgencias_reevaluaciones_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='esp_aminas',
            field=models.TextField(blank=True, null=True, verbose_name='Especifique uso de aminas'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='uso_aminas',
            field=models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=10, null=True, verbose_name='Uso de aminas'),
        ),
    ]
