# Generated by Django 4.1.1 on 2022-09-17 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0055_urgencias_reevaluaciones_esp_aminas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='pvc',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
