# Generated by Django 4.1.1 on 2022-09-17 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0056_urgencias_reevaluaciones_pvc'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='antihipert',
            field=models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], max_length=10, null=True, verbose_name='Uso de antihipertensivos'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='esp_aht',
            field=models.TextField(blank=True, null=True, verbose_name='Especifique uso de antihipertenivos'),
        ),
    ]
