# Generated by Django 4.1.1 on 2022-09-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0057_urgencias_reevaluaciones_antihipert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='FUR',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Gestas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Menarca',
            field=models.CharField(blank=True, help_text='Menarca', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='Partos',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='mast',
            field=models.DateField(blank=True, null=True, verbose_name='Última mastografía'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='obsgin',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones Genecoobstétricas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='pap',
            field=models.DateField(blank=True, null=True, verbose_name='Último Pappaniclocaou'),
        ),
        migrations.AddField(
            model_name='reevaluacion',
            name='genero',
            field=models.CharField(blank=True, choices=[('FEM', 'Femenino'), ('MASC', 'Masculino')], max_length=4, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='urgencias',
            name='genero',
            field=models.CharField(blank=True, choices=[('FEM', 'Femenino'), ('MASC', 'Masculino')], max_length=4, null=True, verbose_name='Género'),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='genero',
            field=models.CharField(blank=True, choices=[('FEM', 'Femenino'), ('MASC', 'Masculino')], max_length=4, null=True, verbose_name='Género'),
        ),
    ]
