# Generated by Django 4.1.1 on 2022-09-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0059_urgencias_reevaluaciones_obs_neur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Anotaciones generales'),
        ),
    ]
