# Generated by Django 4.1.1 on 2022-09-19 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0060_alter_urgencias_reevaluaciones_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Cl',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
