# Generated by Django 4.1.1 on 2022-09-21 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0063_paciente_esp_otro_alter_paciente_especialidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='esp_otro',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='urgencias_reevaluaciones',
            name='Cl',
        ),
    ]
