# Generated by Django 4.1.1 on 2022-09-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0064_remove_paciente_esp_otro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='esp_otro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Especifique otro'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina General', 'Medicina General'), ('Urgenciasas', 'Urgencias'), ('Medicina Interna', 'Medicina Interna'), ('Intensivista', 'Intensivista'), ('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Neurocirugía', 'Neurocirugía'), ('Ortopedia', 'Ortopedia'), ('Ginecología', 'Ginecología'), ('Gastroenterología', 'Gastroenterología'), ('Nefrología', 'Nefrología'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='Cl',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='actual_situation',
            field=models.TextField(blank=True, null=True, verbose_name='Situación Actual y Exploración'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='diagnosis',
            field=models.TextField(blank=True, null=True, verbose_name='Diagnósticos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='gender',
            field=models.CharField(blank=True, choices=[('FEM', 'Femenino'), ('MASC', 'Masculino')], max_length=4, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='immediate_background',
            field=models.TextField(blank=True, null=True, verbose_name='Padecimiento, Razón de Abordaje o Situación Actual'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='txs',
            field=models.TextField(blank=True, null=True, verbose_name='Manejos y Tratamientos'),
        ),
    ]
