# Generated by Django 4.1.1 on 2022-10-14 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0065_paciente_esp_otro_paciente_especialidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='PaFI',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='RASS',
            field=models.CharField(blank=True, choices=[('+4 Combativo', '+4 Combativo'), ('+3 Muy agitado', '+3 Muy agitado'), ('+2 agitado', '+2 Agitado'), ('+1 inquieto', '+1 Inquieto'), ('0 Despierto y Tranquilo', '0 Despierto y tranuilo'), ('-1 somnoliento', '-1 Somnoliento'), ('-2 sedación leve', '-2 Sedación leve'), ('-3 sedación moderada', '-3 Sedación moderada'), ('RASS -4 sedación profunda', 'RASS -4 Sedación profunda'), ('-5 sin respuesta', '-5 Sin respuesta')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='urgencias_reevaluaciones',
            name='vent_mec',
            field=models.CharField(blank=True, choices=[('POSITIVO', 'Positivo'), ('NEGATIVO', 'Negativo')], default='NEGATIVO', max_length=10, null=True, verbose_name='Ventilación Mecánica'),
        ),
    ]
