# Generated by Django 4.1.1 on 2022-09-26 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultorio', '0065_paciente_esp_otro_paciente_especialidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultorio_paciente', to=settings.AUTH_USER_MODEL),
        ),
    ]
