# Generated by Django 4.1.1 on 2022-09-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0066_paciente_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='user',
            new_name='dr',
        ),
    ]
