# Generated by Django 4.1.1 on 2022-09-26 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultorio', '0067_rename_user_paciente_dr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='dr',
        ),
        migrations.AddField(
            model_name='paciente',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consultorio_pacientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
