# Generated by Django 4.1.1 on 2022-10-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0067_urgencias_reevaluaciones_rx_descripcion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urgencias_reevaluaciones',
            old_name='interconsulta',
            new_name='interconsultante1',
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='interconsultante2',
            field=models.CharField(blank=True, choices=[('Medicina Interna', 'Medicina Interna'), ('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Neurocirugía', 'Neurocirugía'), ('Ortopedia', 'Ortopedia'), ('Ginecología', 'Ginecología'), ('Gastroenterología', 'Gastroenterología'), ('Nefrología', 'Nefrología'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='interconsultante3',
            field=models.CharField(blank=True, choices=[('Medicina Interna', 'Medicina Interna'), ('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Neurocirugía', 'Neurocirugía'), ('Ortopedia', 'Ortopedia'), ('Ginecología', 'Ginecología'), ('Gastroenterología', 'Gastroenterología'), ('Nefrología', 'Nefrología'), ('Otro', 'Otro')], max_length=20, null=True),
        ),
    ]
