# Generated by Django 4.1.1 on 2022-09-29 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0068_remove_paciente_dr_paciente_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='author',
        ),
    ]
