# Generated by Django 4.1.1 on 2022-12-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0068_rename_interconsulta_urgencias_reevaluaciones_interconsultante1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='RECOMENDACIONES',
        ),
        migrations.AddField(
            model_name='paciente',
            name='sp_consideration',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Consideraciones Especiales'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='esp_otro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Especifique otro interconsultante'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina General', 'Medicina General'), ('Urgenciasas', 'Urgencias'), ('Medicina Interna', 'Medicina Interna'), ('Intensivista', 'Intensivista'), ('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Neurocirugía', 'Neurocirugía'), ('Ortopedia', 'Ortopedia'), ('Ginecología', 'Ginecología'), ('Gastroenterología', 'Gastroenterología'), ('Nefrología', 'Nefrología'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Especialidad de Interconsulta'),
        ),
    ]
