# Generated by Django 4.1.1 on 2022-12-02 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0069_remove_paciente_recomendaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='actual_situation',
            field=models.TextField(blank=True, null=True, verbose_name='Hábitus exterior y Exploración'),
        ),
    ]
