# Generated by Django 4.1.1 on 2022-12-02 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0070_alter_paciente_actual_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='Cesareas',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Cesáreas'),
        ),
    ]
