# Generated by Django 4.1.1 on 2022-12-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0071_paciente_cesareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medications_list',
            field=models.TextField(blank=True, null=True, verbose_name='Lista de Medicamentos actuales'),
        ),
    ]
