# Generated by Django 4.1.7 on 2023-02-21 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0072_paciente_medications_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urgencias_reevaluaciones',
            old_name='FrIO2',
            new_name='FIO2',
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='SaFI02',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.21, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='urgencias_reevaluaciones',
            name='SaPaFI',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=6, null=True),
        ),
    ]
