# Generated by Django 4.1.7 on 2023-02-21 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0073_rename_frio2_urgencias_reevaluaciones_fio2_and_more'),
        ('consultorio', '0074_alter_urgencias_reevaluaciones_pit'),
    ]

    operations = [
    ]
