# Generated by Django 4.1.7 on 2023-02-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0075_merge_20230220_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='Imagenología1',
            new_name='Doc1',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Imagenología2',
            new_name='Doc2',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Imagenología3',
            new_name='Doc3',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Labs1',
            new_name='Doc4',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='Labs2',
            new_name='Doc5',
        ),
    ]
