# Generated by Django 4.1.7 on 2023-02-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0076_rename_imagenología1_paciente_doc1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reevaluacion',
            old_name='Imagenología1',
            new_name='Doc1',
        ),
        migrations.RenameField(
            model_name='reevaluacion',
            old_name='Imagenología2',
            new_name='Doc2',
        ),
        migrations.RenameField(
            model_name='reevaluacion',
            old_name='Imagenología3',
            new_name='Doc3',
        ),
        migrations.RenameField(
            model_name='reevaluacion',
            old_name='Labs1',
            new_name='Doc4',
        ),
        migrations.RenameField(
            model_name='reevaluacion',
            old_name='Labs2',
            new_name='Doc5',
        ),
    ]
