# Generated by Django 4.1.7 on 2023-02-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0077_rename_imagenología1_reevaluacion_doc1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias',
            name='Doc1',
            field=models.FileField(blank=True, help_text='formato jpg, jpge', null=True, upload_to='Urgencias'),
        ),
        migrations.AddField(
            model_name='urgencias',
            name='Doc2',
            field=models.FileField(blank=True, help_text='formato jpg, jpge', null=True, upload_to='Urgencias'),
        ),
        migrations.AddField(
            model_name='urgencias',
            name='Doc3',
            field=models.FileField(blank=True, help_text='formato jpg, jpge', null=True, upload_to='Urgencias'),
        ),
        migrations.AddField(
            model_name='urgencias',
            name='Doc4',
            field=models.FileField(blank=True, help_text='formato pdf, jpg, jpge', null=True, upload_to='Urgencias'),
        ),
        migrations.AddField(
            model_name='urgencias',
            name='Doc5',
            field=models.FileField(blank=True, help_text='formato pdf, jpg, jpge', null=True, upload_to='Urgencias'),
        ),
        migrations.AddField(
            model_name='urgencias',
            name='recetas',
            field=models.FileField(blank=True, help_text='formato pdf, jpg, jpge', null=True, upload_to='Urgencias', verbose_name='Recetas'),
        ),
    ]
