# Generated by Django 4.1.7 on 2023-02-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0078_urgencias_doc1_urgencias_doc2_urgencias_doc3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urgencias',
            name='saturacion',
            field=models.IntegerField(blank=True, null=True, verbose_name='Sa02'),
        ),
    ]
