# Generated by Django 4.1.7 on 2023-02-21 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0079_alter_urgencias_saturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='urgencias',
            name='esp_otro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Especifique otro interconsultante'),
        ),
        migrations.AddField(
            model_name='urgencias',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina General', 'Medicina General'), ('Urgencias', 'Urgencias'), ('Medicina Interna', 'Medicina Interna'), ('Intensivista', 'Intensivista'), ('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Neurocirugía', 'Neurocirugía'), ('Ortopedia', 'Ortopedia'), ('Ginecología', 'Ginecología'), ('Gastroenterología', 'Gastroenterología'), ('Nefrología', 'Nefrología'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Especialidad de Interconsulta'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('Medicina General', 'Medicina General'), ('Urgencias', 'Urgencias'), ('Medicina Interna', 'Medicina Interna'), ('Intensivista', 'Intensivista'), ('Cirugía', 'Cirugía'), ('Cardiología', 'Cardiología'), ('Neurología', 'Neurología'), ('Neurocirugía', 'Neurocirugía'), ('Ortopedia', 'Ortopedia'), ('Ginecología', 'Ginecología'), ('Gastroenterología', 'Gastroenterología'), ('Nefrología', 'Nefrología'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Especialidad de Interconsulta'),
        ),
    ]
