# Generated by Django 4.1.7 on 2023-03-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0081_paciente_athma'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=100, null=True, verbose_name='Tipo y Grupo Sanguíneo'),
        ),
    ]
