# Generated by Django 4.1.7 on 2023-03-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultorio', '0082_paciente_blood_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='Doc1',
            field=models.FileField(blank=True, help_text='formato jpg, jpge, pdf', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Doc2',
            field=models.FileField(blank=True, help_text='formato jpg, jpge, pdf', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Doc3',
            field=models.FileField(blank=True, help_text='formato jpg, jpge, pdf', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Doc4',
            field=models.FileField(blank=True, help_text='formato jpg, jpge, pdf', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='Doc5',
            field=models.FileField(blank=True, help_text='formato jpg, jpge, pdf', null=True, upload_to='Paciente/'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='recetas',
            field=models.FileField(blank=True, help_text='formato jpg, jpge, pdf', null=True, upload_to='Paciente/', verbose_name='Recetas'),
        ),
    ]
